opam-version: "1"
version: "4.04.0"
src: "https://github.com/mshinwell/ocaml/tarball/gdb-names-gpr"
build: [
  ["./configure" "-prefix" "%{prefix}%" "-flambda" "-no-ocamldoc" "-cc" "gcc -fPIC" "-aspp" "gcc -c -fPIC" ]
  ["%{make}%" "world"]
  ["%{make}%" "world.opt"]
  ["%{make}%" "install"]
]
packages: ["base-unix" "base-bigarray" "base-threads"]
env: [
  [CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]
]
